# Separator needed for jackson to deserialize it as an object
---
# The command prefixes
prefixes: ["!", "?"]
botToken: "your token"
# the url for the database connection
dburl: "jdbc:sqlite:tjbot.sqlite"

# channel for modmail
moderationChannel: "your channel"

# Command settings
commands:
  # Configuration for the free command
  free:
    # The regex used to detect help channels for the free command
    helpChannelRegex: ".*"

